import { useParams } from 'react-router-dom'
import data from '../data/recipes.json'
import { AlertTriangle, Clock, Users } from 'lucide-react'
export default function RecipeDetail(){const {id}=useParams();const r=data.recipes.find(x=>x.id===id);if(!r)return <div className="card">Recipe not found.</div>
let num=0;return <div className="space-y-4"><section className="rounded-3xl bg-navy text-white p-6"><h1 className="text-3xl font-extrabold">{r.title}</h1><p className="opacity-80 mt-2">{r.description}</p><div className="flex flex-wrap gap-2 mt-4"><span className="badge bg-white/15 text-white"><Clock size={12}/>{r.prepTime} prep</span><span className="badge bg-white/15 text-white">{r.cookTime} cook</span><span className="badge bg-white/15 text-white"><Users size={12}/>{r.servings}</span>{r.glutenFree&&<span className="badge bg-amber-300 text-amber-900">GF</span>}</div></section>
{r.gfOption&&<div className="bg-amber-50 border border-amber-200 rounded-2xl p-4 flex gap-3"><AlertTriangle className="text-amber-600"/><div><b>Gluten-free option</b><p className="text-sm">{r.gfOption}</p></div></div>}
<section className="card"><h2 className="font-extrabold text-navy text-xl">Ingredients</h2><ul className="mt-3 space-y-2">{r.ingredients.map(i=><li key={i} className={/flour|panko|bread|pasta|crouton|worcestershire/i.test(i)&&!r.glutenFree?'bg-amber-50 border border-amber-200 rounded-xl p-2':'border-b py-2'}>{i}</li>)}</ul></section>
{r.tempMilestones?.length>0&&<section className="card"><h2 className="font-extrabold text-navy text-xl">Temperature milestones</h2><div className="mt-3 space-y-2">{r.tempMilestones.map(x=><div key={x.temp} className="flex justify-between"><span className="font-bold text-red-600">{x.temp}</span><span>{x.action}</span></div>)}</div></section>}
<section className="card"><h2 className="font-extrabold text-navy text-xl">Instructions</h2><div className="mt-3 space-y-3">{r.instructions.map(s=>s.startsWith('---')?<h3 key={s} className="section-title text-forest pt-2">{s.replace('---','')}</h3>:<div key={s} className="flex gap-3"><span className="w-7 h-7 rounded-full bg-forest text-white flex items-center justify-center text-sm shrink-0">{++num}</span><p>{s}</p></div>)}</div></section></div>}
