import { useMemo, useState } from 'react'
import { BedDouble, Save, Users } from 'lucide-react'
import { allSleepingSpaces, loadV3, profilePresentOnNight, saveV3 } from '../utils/v3Store'
export default function Accommodations(){
 const [state,setState]=useState(loadV3)
 const nights=state.days.slice(0,-1).map(d=>d.date)
 const [night,setNight]=useState(nights[0])
 const spaces=allSleepingSpaces(state).filter(s=>s.active)
 const attendanceMap=Object.fromEntries(state.attendance.map(a=>[a.profileId,a]))
 const profiles=state.profiles.filter(p=>attendanceMap[p.id]?.needsAccommodation&&profilePresentOnNight(attendanceMap[p.id],night))
 const assigned=state.bedAssignments[night]||{}
 const assignedIds=new Set(Object.values(assigned).flat())
 const setActive=(id,active)=>setState(s=>({...s,accommodations:s.accommodations.map(a=>a.id===id?{...a,active}:a)}))
 const assign=(spaceId,oldPersonId,personId)=>setState(s=>{const nightMap={...(s.bedAssignments[night]||{})};if(oldPersonId)for(const id of Object.keys(nightMap))nightMap[id]=nightMap[id].filter(x=>x!==oldPersonId);if(personId){for(const id of Object.keys(nightMap))nightMap[id]=nightMap[id].filter(x=>x!==personId);nightMap[spaceId]=[...(nightMap[spaceId]||[]),personId]}return {...s,bedAssignments:{...s.bedAssignments,[night]:nightMap}}})
 return <div className="space-y-4"><div className="flex justify-between gap-3"><div><h1 className="page-title">Nightly Bed Planner</h1><p className="text-stone">Assign people to sleeping spaces, not just rooms.</p></div><button onClick={()=>saveV3(state)} className="btn-primary flex items-center gap-2"><Save size={17}/>Save beds</button></div>
 <section className="card"><p className="section-title">Active accommodations for this Gathering</p><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2 mt-3">{state.accommodations.map(a=><label key={a.id} className="bg-cream rounded-xl p-3 flex gap-3 items-center"><input type="checkbox" checked={a.active} onChange={e=>setActive(a.id,e.target.checked)}/><span><b>{a.name}</b><p className="text-xs text-stone">{a.type}</p></span></label>)}</div></section>
 <div className="flex gap-2 overflow-x-auto">{nights.map(n=><button key={n} onClick={()=>setNight(n)} className={`px-4 py-2 rounded-full whitespace-nowrap ${night===n?'bg-forest text-white':'bg-white'}`}>{new Date(`${n}T12:00`).toLocaleDateString('en-CA',{weekday:'short',month:'short',day:'numeric'})} night</button>)}</div>
 <div className="bg-amber-50 border border-amber-200 rounded-2xl p-4"><b>{profiles.length} people need accommodation tonight</b><p className="text-sm text-stone mt-1">{profiles.filter(p=>!assignedIds.has(p.id)).length} remain unassigned.</p></div>
 <div className="space-y-3">{state.accommodations.filter(a=>a.active).map(a=><section key={a.id} className="card"><div className="flex justify-between"><div><p className="section-title">{a.type}</p><h2 className="text-xl font-extrabold text-navy">{a.name}</h2></div><span className="badge-forest"><BedDouble size={12}/>{a.rooms.flatMap(r=>r.spaces).reduce((n,s)=>n+s.capacity,0)} spaces</span></div><div className="grid lg:grid-cols-2 gap-3 mt-4">{a.rooms.flatMap(r=>r.spaces.map(s=>({room:r.name,...s}))).map(space=>{const occupants=assigned[space.id]||[],over=occupants.length>space.capacity;return <div key={space.id} className={`rounded-2xl p-3 border ${over?'border-red-400 bg-red-50':'border-stone/15 bg-cream'}`}><div className="flex justify-between"><div><b>{space.room} — {space.name}</b><p className="text-xs text-stone">Capacity {space.capacity}</p></div><span className={`badge ${over?'bg-red-100 text-red-700':'bg-white text-navy'}`}>{occupants.length}/{space.capacity}</span></div><div className="space-y-2 mt-3">{Array.from({length:Math.max(space.capacity,occupants.length)}).map((_,i)=><select key={i} value={occupants[i]||''} onChange={e=>assign(space.id,occupants[i]||'',e.target.value)} className="w-full p-2 border rounded-xl bg-white"><option value="">Empty</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>)}</div></div>})}</div></section>)}</div>
 {profiles.filter(p=>!assignedIds.has(p.id)).length>0&&<section className="card"><p className="section-title">Unassigned tonight</p><div className="flex flex-wrap gap-2 mt-2">{profiles.filter(p=>!assignedIds.has(p.id)).map(p=><span className="badge-gf" key={p.id}>{p.name}</span>)}</div></section>}</div>
}
