import { useMemo, useState } from 'react'
import { Check, Database, ListChecks, Pencil, Plus, RotateCcw, Search, Trash2, X } from 'lucide-react'
import baseData from '../data/baseGroceries.json'
import { getEventGeneratedGroceries } from '../utils/eventGroceryEngine'
import { useEvent } from '../context/EventContext'
import { deleteGroceryItem, getGroceryLibrary, normalizeUnit, packageSuggestion, saveGroceryItem } from '../utils/groceryLibrary'

const stateKey='main-river-trip-grocery-state-v21'
const manualKey='main-river-manual-groceries-v21'
const baseMigrationKey='main-river-base-list-retired-v37'
const categories=['Meat','Seafood','Produce','Dairy','Deli','Bakery','Pantry','Frozen','Drinks','Snacks','Household','Other']
const emptyForm={groceryItemId:'',name:'',quantity:1,unit:'each',category:'Produce',notes:'',gf:false,assignedTo:'',createNew:false,search:''}
const emptyLibraryForm={id:'',name:'',aliasesText:'',category:'Pantry',subcategory:'Other',defaultPurchaseUnit:'package',packageSize:1,packageUnit:'each',allowedUnitsText:'each'}

const normalizeCategory=value=>{
 const text=(value||'Other').toLowerCase()
 if(text.includes('meat'))return 'Meat';if(text.includes('seafood'))return 'Seafood';if(text.includes('produce'))return 'Produce'
 if(text.includes('dairy'))return 'Dairy';if(text.includes('deli'))return 'Deli';if(text.includes('bakery')||text.includes('breakfast'))return 'Bakery'
 if(text.includes('pantry')||text.includes('condiment')||text.includes('spice'))return 'Pantry';if(text.includes('frozen'))return 'Frozen'
 if(text.includes('drink')||text.includes('beverage')||text.includes('liquor'))return 'Drinks';if(text.includes('snack'))return 'Snacks'
 if(text.includes('house')||text.includes('clean')||text.includes('paper'))return 'Household';return 'Other'
}

function loadManualItems(){
 let existing=[]
 try{existing=JSON.parse(localStorage.getItem(manualKey)||'[]')}catch{}
 if(localStorage.getItem(baseMigrationKey))return existing
 let edits={},custom=[]
 try{edits=JSON.parse(localStorage.getItem('cottage-base-groceries-edits')||'{}')}catch{}
 try{custom=JSON.parse(localStorage.getItem('cottage-custom-base-groceries')||'[]')}catch{}
 const builtIns=baseData.categories.flatMap(section=>section.items.map(item=>({...item,...(edits[item.id]||{}),category:normalizeCategory(section.name)})))
 const migrated=[...builtIns,...custom].filter(item=>Number(item.quantity)>0).map((item,index)=>({
  id:`manual-base-migration-${item.id||index}`,groceryItemId:'',name:item.name,quantity:Number(item.quantity),unit:normalizeUnit(item.unit),category:normalizeCategory(item.category),notes:item.notes||'',gf:Boolean(item.gf),assignedTo:'',migratedFromBase:true
 }))
 const ids=new Set(existing.map(item=>item.id))
 const next=[...existing,...migrated.filter(item=>!ids.has(item.id))]
 localStorage.setItem(manualKey,JSON.stringify(next));localStorage.setItem(baseMigrationKey,'1')
 return next
}

export default function Groceries(){
 const {activeEvent,profiles}=useEvent()
 const [mode,setMode]=useState('trip'),[view,setView]=useState('all'),[personFilter,setPersonFilter]=useState(''),[categoryFilter,setCategoryFilter]=useState('All')
 const [showAdd,setShowAdd]=useState(false),[form,setForm]=useState(emptyForm),[library,setLibrary]=useState(()=>getGroceryLibrary())
 const [libraryForm,setLibraryForm]=useState(emptyLibraryForm),[showLibraryForm,setShowLibraryForm]=useState(false),[librarySearch,setLibrarySearch]=useState(''),[listSearch,setListSearch]=useState(''),[libraryFormOriginal,setLibraryFormOriginal]=useState('')
 const [manualItems,setManualItems]=useState(loadManualItems),[itemState,setItemState]=useState(()=>JSON.parse(localStorage.getItem(stateKey)||'{}'))
 const guests=(activeEvent?.attendance||[]).map(row=>profiles.find(profile=>profile.id===row.profileId)).filter(Boolean).map(profile=>({id:profile.id,name:profile.name}))
 const saveState=next=>{setItemState(next);localStorage.setItem(stateKey,JSON.stringify(next))},patchState=(id,patch)=>saveState({...itemState,[id]:{...(itemState[id]||{}),...patch}})
 const saveManual=next=>{setManualItems(next);localStorage.setItem(manualKey,JSON.stringify(next))}
 const generated=getEventGeneratedGroceries(activeEvent).map(item=>({...item,category:normalizeCategory(item.department),sourceType:'recipe',sourceLabel:'Recipe generated',purchaseSuggestion:packageSuggestion(item)}))
 const manual=manualItems.map(item=>({...item,category:normalizeCategory(item.category),sourceType:'manual',sourceLabel:item.migratedFromBase?'Moved from former Base List':'Added grocery item'}))
 const allItems=[...generated,...manual].map(item=>({...item,...(itemState[item.id]||{})})),purchasedCount=allItems.filter(item=>item.purchased).length,remainingCount=allItems.length-purchasedCount
 const visible=allItems.filter(item=>{const q=listSearch.trim().toLowerCase();if(q&&![item.name,item.notes,item.shoppingNote,item.category,item.subcategory,...(item.aliasesMerged||[]),...(item.sources||[]).flatMap(source=>[source.recipe,source.meal,source.originalName])].filter(Boolean).join(' ').toLowerCase().includes(q))return false;if(view==='outstanding'&&item.purchased)return false;if(view==='purchased'&&!item.purchased)return false;if(view==='unassigned'&&item.assignedTo)return false;if(view==='person'&&item.assignedTo!==personFilter)return false;if(categoryFilter!=='All'&&item.category!==categoryFilter)return false;return true})
 const grouped=visible.reduce((acc,item)=>{(acc[item.category]??=[]).push(item);return acc},{})
 const resetPurchased=()=>{const next={};for(const [id,value] of Object.entries(itemState))next[id]={...value,purchased:false};saveState(next)}
 const chooseLibraryItem=item=>setForm({...form,groceryItemId:item.id,name:item.name,category:normalizeCategory(item.category),unit:item.allowedUnits?.[0]||item.packageUnit||'each',search:item.name,createNew:false})
 const addItem=()=>{
  if(!form.name.trim())return
  let groceryItem=library.find(item=>item.id===form.groceryItemId)
  if(form.createNew){groceryItem=saveGroceryItem({name:form.name.trim(),aliases:[],category:form.category,subcategory:'Other',defaultPurchaseUnit:'package',packageSize:1,packageUnit:normalizeUnit(form.unit),allowedUnits:[normalizeUnit(form.unit)]});setLibrary(getGroceryLibrary())}
  const item={id:`manual-${Date.now()}`,groceryItemId:groceryItem?.id||'',name:groceryItem?.name||form.name.trim(),quantity:Number(form.quantity)||1,unit:normalizeUnit(form.unit)||'each',category:groceryItem?.category||form.category,notes:form.notes.trim(),gf:form.gf,assignedTo:form.assignedTo}
  saveManual([...manualItems,item]);setForm(emptyForm);setShowAdd(false)
 }
 const openLibraryEditor=item=>{const next=item?{...item,aliasesText:(item.aliases||[]).join('\n'),allowedUnitsText:(item.allowedUnits||[]).join(', ')}:{...emptyLibraryForm};setLibraryForm(next);setLibraryFormOriginal(JSON.stringify(next));setShowLibraryForm(true)}
 const closeLibraryEditor=()=>{if(JSON.stringify(libraryForm)!==libraryFormOriginal&&!confirm('Discard unsaved Grocery Library changes?'))return;setShowLibraryForm(false);setLibraryForm(emptyLibraryForm);setLibraryFormOriginal('')}
 const saveLibraryRecord=()=>{if(!libraryForm.name.trim())return;saveGroceryItem({...libraryForm,name:libraryForm.name.trim(),aliases:libraryForm.aliasesText.split('\n').map(v=>v.trim()).filter(Boolean),packageSize:Number(libraryForm.packageSize)||0,allowedUnits:libraryForm.allowedUnitsText.split(',').map(v=>normalizeUnit(v.trim())).filter(Boolean)});setLibrary(getGroceryLibrary());setShowLibraryForm(false);setLibraryForm(emptyLibraryForm);setLibraryFormOriginal('')}
 const removeLibraryRecord=id=>{if(confirm('Delete this Grocery Library item? Existing recipes keep their ingredient names but lose the standard link.'))setLibrary(deleteGroceryItem(id))}
 const filteredLibrary=library.filter(item=>{const q=librarySearch.trim().toLowerCase();return !q||[item.name,item.category,item.subcategory,...(item.aliases||[])].join(' ').toLowerCase().includes(q)})
 const addMatches=useMemo(()=>{const q=form.search.trim().toLowerCase();return (q?library.filter(item=>[item.name,...(item.aliases||[])].join(' ').toLowerCase().includes(q)):library).slice(0,8)},[form.search,library])

 return <div className="space-y-4">
  <div className="flex flex-wrap justify-between gap-3"><div><h1 className="page-title">{mode==='trip'?'Trip Grocery List':'Grocery Library'}</h1><p className="text-stone">{mode==='trip'?`${purchasedCount} purchased · ${remainingCount} remaining · ${allItems.length} total`:'Standard items, aliases, categories, compatible units and common package sizes.'}</p></div><div className="flex gap-2">{mode==='trip'?<><button onClick={()=>{setForm(emptyForm);setShowAdd(true)}} className="btn-primary flex items-center gap-2"><Plus size={18}/>Add Grocery Item</button><button onClick={resetPurchased} className="p-2 bg-white rounded-xl" title="Clear purchased checks"><RotateCcw/></button></>:<button onClick={()=>openLibraryEditor(null)} className="btn-primary flex items-center gap-2"><Plus size={18}/>New Grocery Item</button>}</div></div>
  <div className="grid grid-cols-2 gap-2 bg-white rounded-2xl p-1 shadow-sm"><button onClick={()=>setMode('trip')} className={`rounded-xl px-3 py-3 font-semibold flex justify-center items-center gap-2 ${mode==='trip'?'bg-forest text-white':'text-stone'}`}><ListChecks size={18}/>Trip Grocery List</button><button onClick={()=>setMode('library')} className={`rounded-xl px-3 py-3 font-semibold flex justify-center items-center gap-2 ${mode==='library'?'bg-forest text-white':'text-stone'}`}><Database size={18}/>Grocery Library</button></div>
  {mode==='trip'?<>
   <div className="card flex gap-2 items-center"><Search className="text-stone"/><input value={listSearch} onChange={e=>setListSearch(e.target.value)} className="w-full outline-none bg-transparent" placeholder="Search trip groceries, recipes, aliases or notes..."/></div>
   <div className="h-3 bg-white rounded-full overflow-hidden"><div className="h-full bg-forest" style={{width:`${allItems.length?purchasedCount/allItems.length*100:0}%`}}/></div>
   <div className="bg-forest/5 border border-forest/15 rounded-2xl p-4 text-sm"><b>One shared running list</b><p className="text-stone mt-1">Active meal recipes generate groceries automatically. Add anything else by choosing a standard Grocery Library item or creating one.</p></div>
   <div className="flex gap-2 overflow-x-auto">{[['all','All'],['outstanding','Outstanding'],['purchased','Purchased'],['unassigned','Unassigned'],['person','By Person']].map(([id,label])=><button key={id} onClick={()=>setView(id)} className={`px-4 py-2 rounded-full whitespace-nowrap font-semibold ${view===id?'bg-forest text-white':'bg-white'}`}>{label}</button>)}</div>
   {view==='person'&&<select value={personFilter} onChange={e=>setPersonFilter(e.target.value)} className="w-full sm:w-72 bg-white border rounded-xl p-3"><option value="">Choose a guest</option>{guests.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select>}
   <div className="flex gap-2 overflow-x-auto">{['All',...categories].map(category=><button key={category} onClick={()=>setCategoryFilter(category)} className={`px-3 py-2 rounded-full whitespace-nowrap text-sm font-semibold ${categoryFilter===category?'bg-navy text-white':'bg-white text-stone'}`}>{category}</button>)}</div>
   {Object.entries(grouped).map(([category,items])=><section key={category} className="card"><h2 className="section-title mb-2">{category}</h2>{items.map(item=>{const guest=guests.find(g=>g.id===item.assignedTo);return <div key={item.id} className={`py-4 border-b last:border-0 ${item.purchased?'opacity-60':''}`}><div className="flex gap-3 items-start"><button onClick={()=>patchState(item.id,{purchased:!item.purchased})} className={`w-7 h-7 rounded-lg border flex items-center justify-center shrink-0 mt-1 ${item.purchased?'bg-forest border-forest text-white':'border-stone/30'}`}>{item.purchased&&<Check size={17}/>}</button><div className="flex-1 min-w-0"><div className="flex flex-wrap gap-2 items-center"><b className={`text-lg ${item.purchased?'line-through':''}`}>{item.name}</b><span>{item.quantity} {item.unit}</span><span className={`badge ${item.sourceType==='recipe'?'bg-forest/10 text-forest':'bg-wood-100 text-wood-600'}`}>{item.sourceLabel}</span>{item.gf&&<span className="badge-gf">GF</span>}</div><p className="text-xs text-stone mt-1">{item.sourceType==='recipe'&&item.sources?.length?item.sources.map(source=>`${source.recipe} → ${source.meal} (${source.attendance} guests, ${source.scale}×)`).join(' • '):item.notes||'No notes'}</p>{item.purchaseSuggestion&&<p className="text-xs font-semibold text-forest mt-1">{item.purchaseSuggestion.label}</p>}<div className="grid sm:grid-cols-[240px_1fr] gap-2 mt-3"><label className="text-xs text-stone">Who’s getting this?<select value={item.assignedTo||''} onChange={e=>patchState(item.id,{assignedTo:e.target.value})} className="block w-full mt-1 bg-white border rounded-xl p-2 text-sm text-forest"><option value="">Unassigned</option>{guests.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label className="text-xs text-stone">Shopping note<input value={item.shoppingNote||''} onChange={e=>patchState(item.id,{shoppingNote:e.target.value})} placeholder="Brand, ripeness, size..." className="block w-full mt-1 bg-white border rounded-xl p-2 text-sm"/></label></div>{guest&&<p className="text-xs font-semibold text-navy mt-2">Assigned to {guest.name}</p>}</div>{item.sourceType==='manual'&&<button onClick={()=>saveManual(manualItems.filter(x=>x.id!==item.id))} className="text-stone hover:text-red-600 p-1" title="Delete added item"><Trash2 size={18}/></button>}</div></div>})}</section>)}
   {!visible.length&&<div className="card text-center py-10"><p className="font-semibold text-navy">{view==='person'&&!personFilter?'Choose a guest to view their list.':'No grocery items match this view.'}</p></div>}
  </>:<><div className="card"><input value={librarySearch} onChange={e=>setLibrarySearch(e.target.value)} className="w-full p-3 border rounded-xl" placeholder="Search standard items or aliases..."/></div><div className="grid md:grid-cols-2 gap-3">{filteredLibrary.map(item=><section key={item.id} className="card"><div className="flex justify-between gap-3 items-start"><div><h2 className="text-lg font-extrabold text-navy">{item.name}</h2><p className="text-sm text-stone">{item.category} → {item.subcategory}</p></div><div className="flex gap-2"><button onClick={()=>openLibraryEditor(item)} className="px-3 py-2 bg-cream rounded-xl font-semibold flex items-center gap-1"><Pencil size={15}/>Edit</button><button onClick={()=>removeLibraryRecord(item.id)} className="p-2 text-red-700"><Trash2 size={16}/></button></div></div><div className="mt-3"><span className="section-title">Aliases</span><div className="flex flex-wrap gap-1 mt-1">{(item.aliases||[]).map(alias=><span key={alias} className="badge bg-navy/10 text-navy">{alias}</span>)}{!item.aliases?.length&&<span className="text-xs text-stone">No aliases</span>}</div></div><div className="grid grid-cols-2 gap-2 mt-4 text-sm"><div className="bg-cream rounded-xl p-3"><b>Package</b><p>{item.packageSize||'—'} {item.packageUnit||''} {item.defaultPurchaseUnit||''}</p></div><div className="bg-cream rounded-xl p-3"><b>Recipe units</b><p>{(item.allowedUnits||[]).join(', ')||'Not set'}</p></div></div></section>)}</div></>}

  {showAdd&&<div className="fixed inset-0 z-[80] bg-black/40 flex items-end sm:items-center justify-center p-4" onClick={()=>setShowAdd(false)}><div className="bg-cream rounded-3xl w-full max-w-xl p-5 max-h-[90vh] overflow-auto" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><h2 className="text-xl font-extrabold text-navy">Add Grocery Item</h2><p className="text-sm text-stone">Choose from the Grocery Library, or create a new standard item.</p></div><button onClick={()=>setShowAdd(false)}><X/></button></div><div className="grid grid-cols-2 gap-2 mt-5"><button onClick={()=>setForm({...emptyForm,search:form.search})} className={`rounded-xl p-3 font-semibold ${!form.createNew?'bg-forest text-white':'bg-white'}`}>Choose from Library</button><button onClick={()=>setForm({...emptyForm,createNew:true})} className={`rounded-xl p-3 font-semibold ${form.createNew?'bg-forest text-white':'bg-white'}`}>Create New Item</button></div>
   {!form.createNew?<div className="mt-4"><input autoFocus value={form.search} onChange={e=>setForm({...form,search:e.target.value,groceryItemId:'',name:''})} className="w-full p-3 rounded-xl bg-white border" placeholder="Search milk, bread, paper towels..."/><div className="mt-2 space-y-2 max-h-56 overflow-auto">{addMatches.map(item=><button key={item.id} onClick={()=>chooseLibraryItem(item)} className={`w-full text-left p-3 rounded-xl border ${form.groceryItemId===item.id?'bg-forest text-white border-forest':'bg-white'}`}><b>{item.name}</b><span className={`block text-xs ${form.groceryItemId===item.id?'text-white/80':'text-stone'}`}>{item.category} · {(item.allowedUnits||[]).join(', ')}</span></button>)}</div></div>:<div className="grid sm:grid-cols-2 gap-3 mt-4"><label className="sm:col-span-2"><span className="section-title">New standard item name</span><input autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="w-full mt-2 p-3 rounded-xl bg-white border" placeholder="Item name"/></label><label><span className="section-title">Category</span><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="w-full mt-2 p-3 rounded-xl bg-white border">{categories.map(x=><option key={x}>{x}</option>)}</select></label><label><span className="section-title">Default unit</span><input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})} className="w-full mt-2 p-3 rounded-xl bg-white border"/></label></div>}
   {(form.groceryItemId||form.createNew)&&<div className="grid sm:grid-cols-2 gap-3 mt-4"><label><span className="section-title">Quantity</span><input type="number" min="0" step="0.5" value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})} className="w-full mt-2 p-3 rounded-xl bg-white border"/></label><label><span className="section-title">Unit</span>{form.groceryItemId?<select value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})} className="w-full mt-2 p-3 rounded-xl bg-white border">{(library.find(item=>item.id===form.groceryItemId)?.allowedUnits||['each']).map(unit=><option key={unit}>{unit}</option>)}</select>:<input value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})} className="w-full mt-2 p-3 rounded-xl bg-white border"/>}</label><label><span className="section-title">Assign to</span><select value={form.assignedTo} onChange={e=>setForm({...form,assignedTo:e.target.value})} className="w-full mt-2 p-3 rounded-xl bg-white border"><option value="">Unassigned</option>{guests.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label><span className="section-title">Notes</span><input value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="w-full mt-2 p-3 rounded-xl bg-white border" placeholder="Brand, type, preference..."/></label><label className="bg-white rounded-2xl p-4 flex gap-3 items-center sm:col-span-2"><input type="checkbox" checked={form.gf} onChange={e=>setForm({...form,gf:e.target.checked})}/><span><b>Gluten-free</b><p className="text-xs text-stone">Show a GF marker.</p></span></label></div>}
   <button onClick={addItem} disabled={!form.name.trim()} className="btn-primary w-full mt-5 disabled:opacity-40">Add to Trip Grocery List</button></div></div>}
  {showLibraryForm&&<div className="fixed inset-0 z-[90] bg-black/40 flex items-end sm:items-center justify-center p-4"><div className="bg-cream rounded-3xl w-full max-w-2xl p-5 max-h-[92vh] overflow-auto"><div className="flex justify-between"><div><h2 className="text-xl font-extrabold text-navy">{libraryForm.id?'Edit Grocery Item':'New Grocery Item'}</h2><p className="text-sm text-stone">One standard record is reused by recipes and trip groceries.</p></div><button onClick={closeLibraryEditor}><X/></button></div><div className="grid sm:grid-cols-2 gap-3 mt-5"><label className="sm:col-span-2"><span className="section-title">Standard name</span><input value={libraryForm.name} onChange={e=>setLibraryForm({...libraryForm,name:e.target.value})} className="w-full mt-1 p-3 border rounded-xl bg-white"/></label><label><span className="section-title">Category</span><input value={libraryForm.category} onChange={e=>setLibraryForm({...libraryForm,category:e.target.value})} className="w-full mt-1 p-3 border rounded-xl bg-white"/></label><label><span className="section-title">Subcategory</span><input value={libraryForm.subcategory} onChange={e=>setLibraryForm({...libraryForm,subcategory:e.target.value})} className="w-full mt-1 p-3 border rounded-xl bg-white"/></label><label className="sm:col-span-2"><span className="section-title">Aliases — one per line</span><textarea value={libraryForm.aliasesText} onChange={e=>setLibraryForm({...libraryForm,aliasesText:e.target.value})} className="w-full mt-1 p-3 border rounded-xl bg-white min-h-28"/></label><label><span className="section-title">Purchase unit</span><input value={libraryForm.defaultPurchaseUnit} onChange={e=>setLibraryForm({...libraryForm,defaultPurchaseUnit:e.target.value})} className="w-full mt-1 p-3 border rounded-xl bg-white"/></label><label><span className="section-title">Package size</span><div className="grid grid-cols-2 gap-2 mt-1"><input type="number" min="0" step="0.01" value={libraryForm.packageSize} onChange={e=>setLibraryForm({...libraryForm,packageSize:e.target.value})} className="p-3 border rounded-xl bg-white"/><input value={libraryForm.packageUnit} onChange={e=>setLibraryForm({...libraryForm,packageUnit:e.target.value})} className="p-3 border rounded-xl bg-white"/></div></label><label className="sm:col-span-2"><span className="section-title">Allowed recipe units — comma separated</span><input value={libraryForm.allowedUnitsText} onChange={e=>setLibraryForm({...libraryForm,allowedUnitsText:e.target.value})} className="w-full mt-1 p-3 border rounded-xl bg-white"/></label></div><div className="grid grid-cols-2 gap-2 mt-5"><button onClick={closeLibraryEditor} className="rounded-xl bg-white border px-4 py-3 font-semibold">Cancel</button><button onClick={saveLibraryRecord} disabled={!libraryForm.name.trim()} className="btn-primary disabled:opacity-40">Save Grocery Item</button></div></div></div>}
 </div>
}
