import { useState } from 'react'
import data from '../data/guests.json'
import week from '../data/week.json'
import { guestsForDate, dateLabel } from '../utils'
export default function Guests(){const [view,setView]=useState('list'), gf=data.guests.filter(g=>g.dietary.includes('gluten-free'))
return <div className="space-y-4"><div><h1 className="page-title">Guests</h1><p className="text-stone">{data.guests.length} people listed • {gf.length} gluten-free</p></div>
<div className="bg-amber-50 border border-amber-200 rounded-2xl p-4"><b>Gluten-free:</b> {gf.map(g=>g.name).join(' and ')}. Use separate utensils and prep areas.</div>
<div className="flex gap-2"><button onClick={()=>setView('list')} className={`px-4 py-2 rounded-full ${view==='list'?'bg-forest text-white':'bg-white'}`}>List</button><button onClick={()=>setView('day')} className={`px-4 py-2 rounded-full ${view==='day'?'bg-forest text-white':'bg-white'}`}>By day</button></div>
{view==='list'?<div className="space-y-2">{data.guests.map(g=><div key={g.id} className="card flex gap-3 items-center"><div className="w-11 h-11 rounded-full bg-navy/10 text-navy font-bold flex items-center justify-center">{g.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div className="flex-1"><b>{g.name}</b><p className="text-xs text-stone">{g.arrival ? `${dateLabel(g.arrival)}–${dateLabel(g.departure)}` : 'Attendance TBD'} {g.notes&&`• ${g.notes}`}</p></div><div className="flex gap-1 flex-wrap justify-end">{g.role&&<span className="badge-navy">{g.role}</span>}{g.dietary.includes('gluten-free')&&<span className="badge-gf">GF</span>}</div></div>)}</div>:
<div className="space-y-3">{week.days.map(d=>{const p=guestsForDate(data.guests,d.date), gfCount=p.filter(g=>g.dietary.includes('gluten-free')).length;return <section className="card" key={d.id}><div className="flex justify-between"><div><b className="text-navy">{d.label}</b><p className="text-xs text-stone">{dateLabel(d.date)}</p></div><span className="badge-forest">{p.length} guests</span></div><div className="flex flex-wrap gap-2 mt-3">{p.map(g=><span key={g.id} className={g.dietary.includes('gluten-free')?'badge-gf':'badge-navy'}>{g.name}</span>)}</div>{gfCount>0&&<p className="text-xs text-amber-700 mt-2">{gfCount} GF guest{gfCount>1?'s':''}</p>}</section>})}</div>}</div>}
