import { useMemo, useState } from 'react'
import { Link2, Save, Users, X } from 'lucide-react'
import { finalMealAttendees, getMealType, loadV3, saveV3 } from '../utils/v3Store'
export default function PlannerV3(){
 const [state,setState]=useState(loadV3)
 const [dayId,setDayId]=useState(state.days[2]?.id||state.days[0].id)
 const day=state.days.find(d=>d.id===dayId)
 const names=Object.fromEntries(state.profiles.map(p=>[p.id,p.name]))
 const recipes=state.structuredRecipes
 const updateSlot=(slotId,patch)=>setState(s=>({...s,days:s.days.map(d=>d.id===day.id?{...d,mealSlots:d.mealSlots.map(slot=>slot.id===slotId?{...slot,...patch}:slot)}:d)}))
 const toggleAttendee=(slot,id,mode)=>{const field=mode==='add'?'manualAdd':'manualRemove',list=slot[field]||[];updateSlot(slot.id,{[field]:list.includes(id)?list.filter(x=>x!==id):[...list,id]})}
 const assignRecipe=(slot,recipeId)=>updateSlot(slot.id,{recipeAssignments:recipeId?[{recipeId,leadProfileId:'',notes:''}]:[]})
 return <div className="space-y-4"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="page-title">Date-specific Meal Planner</h1><p className="text-stone">Meal Slot = Gathering + date + meal type + configured time.</p></div><button onClick={()=>saveV3(state)} className="btn-primary flex items-center gap-2"><Save size={17}/>Save planner</button></div>
 <div className="flex gap-2 overflow-x-auto">{state.days.map(d=><button key={d.id} onClick={()=>setDayId(d.id)} className={`px-4 py-2 rounded-full whitespace-nowrap font-semibold ${dayId===d.id?'bg-forest text-white':'bg-white'}`}>{new Date(`${d.date}T12:00`).toLocaleDateString('en-CA',{weekday:'short',month:'short',day:'numeric'})}</button>)}</div>
 <div className="space-y-3">{day.mealSlots.map(slot=>{const type=getMealType(slot.typeId),attendees=finalMealAttendees(state,day,slot);return <section key={slot.id} className="card"><div className="flex flex-wrap justify-between gap-3"><div><p className="section-title">{type.label}</p><h2 className="text-xl font-extrabold text-navy">{day.date} · {slot.time}</h2><p className="text-sm text-stone">{type.automatic?'Automatic from arrival/departure':'Unassigned by default'}</p></div><span className="badge-forest"><Users size={12}/>{attendees.length} attending</span></div>
 <div className="grid lg:grid-cols-2 gap-4 mt-4"><div><label className="section-title">Meal time</label><input type="time" value={slot.time} onChange={e=>updateSlot(slot.id,{time:e.target.value})} className="w-full mt-2 p-2 border rounded-xl"/><label className="section-title block mt-4">Plan type</label><div className="flex gap-2 mt-2">{['simple','recipes','restaurant'].map(x=><button key={x} onClick={()=>updateSlot(slot.id,{planType:x})} className={`px-3 py-2 rounded-xl capitalize ${slot.planType===x?'bg-navy text-white':'bg-cream'}`}>{x}</button>)}</div>
 {slot.planType==='simple'&&<textarea value={slot.simplePlan} onChange={e=>updateSlot(slot.id,{simplePlan:e.target.value})} className="w-full mt-3 p-3 border rounded-xl"/>}
 {slot.planType==='recipes'&&<div className="mt-3"><label className="section-title">Assigned recipe</label><select value={slot.recipeAssignments?.[0]?.recipeId||''} onChange={e=>assignRecipe(slot,e.target.value)} className="w-full mt-2 p-3 border rounded-xl"><option value="">Unassigned</option>{recipes.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select>{slot.recipeAssignments?.length>0&&<p className="text-xs text-forest mt-2"><Link2 size={12} className="inline"/> Grocery generation active for this Meal Slot.</p>}</div>}
 {slot.planType==='restaurant'&&<input value={slot.restaurant?.name||''} onChange={e=>updateSlot(slot.id,{restaurant:{...(slot.restaurant||{}),name:e.target.value}})} placeholder="Restaurant name" className="w-full mt-3 p-3 border rounded-xl"/>}</div>
 <div><p className="section-title">Final attendees</p><div className="flex flex-wrap gap-2 mt-2">{attendees.map(id=><span key={id} className="badge-navy">{names[id]}</span>)||null}{!attendees.length&&<span className="text-sm text-stone">No one assigned.</span>}</div><details className="mt-4"><summary className="font-semibold text-forest cursor-pointer">Attendance exceptions</summary><div className="mt-3 grid sm:grid-cols-2 gap-2">{state.profiles.map(p=>{const included=attendees.includes(p.id);return <div key={p.id} className="bg-cream rounded-xl p-2 flex justify-between items-center"><span className="text-sm">{p.name}</span><div className="flex gap-1"><button onClick={()=>toggleAttendee(slot,p.id,'add')} className={`px-2 py-1 rounded text-xs ${slot.manualAdd.includes(p.id)?'bg-forest text-white':'bg-white'}`}>Add</button><button onClick={()=>toggleAttendee(slot,p.id,'remove')} className={`px-2 py-1 rounded text-xs ${slot.manualRemove.includes(p.id)?'bg-red-600 text-white':'bg-white'}`}>Exclude</button></div></div>})}</div></details></div></div></section>})}</div></div>
}
